            <div class="row-fluid">
                <div id="sideLeft" class="span3">
                    <div class="well sidebar-nav">
                                        <ul class="nav nav-list">
                        <li class="active">
                            <a href="#">Страны</a>
                        </li>
                        <li>
                            <a href="#">Города</a>
                        </li>
                        <li>
                            <a href="#">Категории</a>
                        </li>
                        <li>
                            <a href="#">Туры</a>
                        </li>
                        <li>
                            <a href="#">Статические страницы</a>
                        </li>
                    </ul>
                        </div>
                </div><!-- .sidebar#sideLeft -->
                <div class="span9">
                        <div class="row-fluid">
<div class="page-header">
<h2>Пример пункта меню в админке</h2>
</div>

<a href="#" class="btn btn-large btn-primary">Добавить</a>
<table class="table table-bordered table-striped">
    <tbody><tr>
        <th class="span10">Название</th>
        <th>Действия</th>
    </tr>
    <tr>
        <td>Украина</td>
            <td>   
                    <a href="/country/ukraine.html" target="_blank" title="Открыть в новом окне" class="btn btn-info"><i class="icon-share-alt icon-white"></i></a>
                    <a href="/admin/country/edit/id/1" title="Редактировать" class="btn btn-success"><i class="icon-edit icon-white"></i></a>
                    <a href="/admin/country/delete/id/1" title="Удалить" class="btn btn-danger"><i class="icon-trash icon-white"></i></a>
            </td>
    </tr>

    <tr>
        <td>Австрия</td>
            <td>   
                    <a href="/country/austria.html" target="_blank" title="Открыть в новом окне" class="btn btn-info"><i class="icon-share-alt icon-white"></i></a>
                    <a href="/admin/country/edit/id/2" title="Редактировать" class="btn btn-success"><i class="icon-edit icon-white"></i></a>
                    <a href="/admin/country/delete/id/2" title="Удалить" class="btn btn-danger"><i class="icon-trash icon-white"></i></a>
            </td>
    </tr>

    <tr>
        <td>Германия</td>
            <td>   
                    <a href="/country/germany.html" target="_blank" title="Открыть в новом окне" class="btn btn-info"><i class="icon-share-alt icon-white"></i></a>
                    <a href="/admin/country/edit/id/3" title="Редактировать" class="btn btn-success"><i class="icon-edit icon-white"></i></a>
                    <a href="/admin/country/delete/id/3" title="Удалить" class="btn btn-danger"><i class="icon-trash icon-white"></i></a>
            </td>
    </tr>

    <tr>
        <td>Венгрия</td>
            <td>   
                    <a href="/country/vengria.html" target="_blank" title="Открыть в новом окне" class="btn btn-info"><i class="icon-share-alt icon-white"></i></a>
                    <a href="/admin/country/edit/id/4" title="Редактировать" class="btn btn-success"><i class="icon-edit icon-white"></i></a>
                    <a href="/admin/country/delete/id/4" title="Удалить" class="btn btn-danger"><i class="icon-trash icon-white"></i></a>
            </td>
    </tr>

    <tr>
        <td>Чехия</td>
            <td>   
                    <a href="/country/chehia.html" target="_blank" title="Открыть в новом окне" class="btn btn-info"><i class="icon-share-alt icon-white"></i></a>
                    <a href="/admin/country/edit/id/5" title="Редактировать" class="btn btn-success"><i class="icon-edit icon-white"></i></a>
                    <a href="/admin/country/delete/id/5" title="Удалить" class="btn btn-danger"><i class="icon-trash icon-white"></i></a>
            </td>
    </tr>

    <tr>
        <td>Великобритания</td>
            <td>   
                    <a href="/country/britain.html" target="_blank" title="Открыть в новом окне" class="btn btn-info"><i class="icon-share-alt icon-white"></i></a>
                    <a href="/admin/country/edit/id/6" title="Редактировать" class="btn btn-success"><i class="icon-edit icon-white"></i></a>
                    <a href="/admin/country/delete/id/6" title="Удалить" class="btn btn-danger"><i class="icon-trash icon-white"></i></a>
            </td>
    </tr>

    <tr>
        <td>Дания</td>
            <td>   
                    <a href="/country/dania.html" target="_blank" title="Открыть в новом окне" class="btn btn-info"><i class="icon-share-alt icon-white"></i></a>
                    <a href="/admin/country/edit/id/7" title="Редактировать" class="btn btn-success"><i class="icon-edit icon-white"></i></a>
                    <a href="/admin/country/delete/id/7" title="Удалить" class="btn btn-danger"><i class="icon-trash icon-white"></i></a>
            </td>
    </tr>

    <tr>
        <td>Гандурас</td>
            <td>   
                    <a href="/country/handuras.html" target="_blank" title="Открыть в новом окне" class="btn btn-info"><i class="icon-share-alt icon-white"></i></a>
                    <a href="/admin/country/edit/id/8" title="Редактировать" class="btn btn-success"><i class="icon-edit icon-white"></i></a>
                    <a href="/admin/country/delete/id/8" title="Удалить" class="btn btn-danger"><i class="icon-trash icon-white"></i></a>
            </td>
    </tr>

    <tr>
        <td>Франция</td>
            <td>   
                    <a href="/country/france.html" target="_blank" title="Открыть в новом окне" class="btn btn-info"><i class="icon-share-alt icon-white"></i></a>
                    <a href="/admin/country/edit/id/9" title="Редактировать" class="btn btn-success"><i class="icon-edit icon-white"></i></a>
                    <a href="/admin/country/delete/id/9" title="Удалить" class="btn btn-danger"><i class="icon-trash icon-white"></i></a>
            </td>
    </tr>

    <tr>
        <td>США</td>
            <td>   
                    <a href="/country/usa.html" target="_blank" title="Открыть в новом окне" class="btn btn-info"><i class="icon-share-alt icon-white"></i></a>
                    <a href="/admin/country/edit/id/10" title="Редактировать" class="btn btn-success"><i class="icon-edit icon-white"></i></a>
                    <a href="/admin/country/delete/id/10" title="Удалить" class="btn btn-danger"><i class="icon-trash icon-white"></i></a>
            </td>
    </tr>

</tbody></table>
</div>                </div><!-- #container-->
            </div><!-- #middle-->