<?php
$title = '4. Основная информация';
$this->headTitle($title);
?>
<h2><?php echo $this->escape($title); ?></h2>
<form id="form1" name="form1" method="post" action="">
<div>Менялись ли ФИО:
<span><label>
  <input type="radio" name="result" id="result" value="1">
  Да</label>
<label>
  <input type="radio" name="result" id="result1" value="0">
  Нет</label></span>
</div>
<div>
<label for="">Предыдущие ФИО:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Место рождения:</label>
<input type="text" name="val1" id="val1">
</div>
<h3>Контактные телефоны</h3>
<div>
<label>Телефон домашний:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Телефон мобильный:</label>
<input type="text" name="val1" id="val1">
</div>

<h3>Паспортные данные</h3>
<div>
<label>Серия:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Номер:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Кем выдан:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Дата выдачи:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Второй документ:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Пропуск Автоваза:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Свидетельство ИП:</label>
<input type="text" name="val1" id="val1">
</div>

<h2>Дополнительная информация</h2>
<div>
<label>Дата регистрации:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Статус жилья:</label>
<input type="text" name="val1" id="val1">
</div>

<h3>Адрес постоянной регистрации</h3>
<div>
<label>Страна:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Область:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Населенный пункт:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Улица:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Дом:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Строение:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Квартира:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Индекс:</label>
<input type="text" name="val1" id="val1">
</div>

<h3>Адрес фактического проживания</h3>
<div>Совпадает с адресом постоянной регистрации:
<span><label>
  <input type="radio" name="result" id="result" value="1">
  Да</label>
<label>
  <input type="radio" name="result" id="result1" value="0">
  Нет</label></span>
</div>
<div>
<label>Страна:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Область:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Населенный пункт:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Улица:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Дом:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Строение:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Квартира:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Индекс:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Образование:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Электронная почта:</label>
<input type="text" name="val1" id="val1">
</div>

<div class="label">Наличие автомобиля в собственности:
<span><label>
  <input type="radio" name="result" id="result" value="1">
  Да</label>
<label>
  <input type="radio" name="result" id="result1" value="0">
  Нет</label></span>
</div>
<div class="label">Судимость:
<span><label>
  <input type="radio" name="result" id="result" value="1">
  Есть</label>
<label>
  <input type="radio" name="result" id="result1" value="0">
  Нет</label></span>
</div>
<h2>Информация о месте работы</h2>
<div>
<label>Место работы:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Должность:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Стаж работы в данной организации:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Адрес организации:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>ФИО непосредственного руководителя или контактного лица в данной организации:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Контактный телефон:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Комментарий:</label>
<input type="text" name="val1" id="val1">
</div>

<h2>Информация о доходах и расходах</h2>
<div>
<label>Постоянный ежемесячный доход:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Дополнительный ежемесячный доход:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Источник дополнительного дохода:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Сумма аванса:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Дата выплаты аванса:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Дата выплаты зарплаты:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Сумма платежей по кредитам:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Сумма платежей по аренде/коммунальным платежам:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Номер карты, наименование банка:</label>
<input type="text" name="val1" id="val1">
</div>

<h2>Информация о семье, родственниках</h2>
<div class="label">Семейное положение:
<span><label>
  <input type="radio" name="result" id="result" value="1">
  женат/замужем</label>
<label>
  <input type="radio" name="result" id="result1" value="0">
  холост</label></span>
</div>
<div>
<label>ФИО супруга/супруги:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Место работы супруга/супруги:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Должность супруга/супруги:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Дети до 21 года:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Иждивенцы:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Контактное лицо, ФИО:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Контактный телефон:</label>
<input type="text" name="val1" id="val1">
</div>
<div>
<label>Совокупный семейный доход:</label>
<input type="text" name="val1" id="val1">
</div>

<input type="submit" value="Далее" class="button white" >
</form>