<?php 
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/bootstrap/css/bootstrap.min.css')
                 ->appendStylesheet($basePath . '/css/style.css')
                 ->appendStylesheet($basePath . '/bootstrap/css/bootstrap-responsive.min.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js');
$this->headScript()->appendFile('http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js');
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript', 
    array('conditional' => 'lt IE9',));

echo $this->doctype()->__invoke('HTML5');
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Admin panel') ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>">Админ-панель</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('adminhome') ?>">
                  <i class="icon-home icon-white"></i> Dashboard
                    </a>
              </li>

                <li class="dropdown" id="menu-products">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu-products">
                        <i class="icon-shopping-cart icon-white"></i>   Продукты
                    <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                    <li><a href="#">Управление</a></li>
                        <li class="divider"></li>
                    <li><a href="#">Группы</a></li>
                    </ul>
                </li>

                <li class="dropdown" id="menu-managers">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu-managers">
                        <i class="icon-cog icon-white"></i>  Менеджеры
                    <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                    <li><a href="#">Управление</a></li>
                        <li class="divider"></li>
                    <li><a href="#">Групы</a></li>
                        <li class="divider"></li>
                    <li><a href="#">Роли</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Разное</a></li>
                    </ul>
                </li>

                <li class="dropdown" id="menu-clients">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu-clients">
                        <i class="icon-user icon-white"></i>
                    Клиенты
                    <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                    <li><a href="#">Управление</a></li>
                        <li class="divider"></li>
                    <li><a href="#">Аттрибуты</a></li>
                        <li class="divider"></li>
                    <li><a href="#">Разное</a></li>
                    </ul>
                </li>

                <li class="dropdown" id="menu-reports">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu-reports">
                        <i class="icon-calendar icon-white"></i> Отчеты
                    <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                    <li><a href="#">Пункт 1</a></li>
                        <li class="divider"></li>
                    <li><a href="#">Пункт 2</a></li>
                        <li class="divider"></li>
                    <li><a href="#">Пункт 3</a></li>
                    </ul>
                </li>

                <li class="dropdown" id="menu-documents">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu-documents">
                        <i class="icon-briefcase icon-white"></i>  Документы
                    <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                    <li><a href="#">Пункт 1</a></li>
                        <li class="divider"></li>
                    <li><a href="#">Пункт 2</a></li>
                        <li class="divider"></li>
                    <li><a href="#">Пункт 3</a></li>
                    </ul>
                </li>

                <li class="dropdown" id="menu-setting">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu-setting">
                        <i class="icon-wrench icon-white"></i>   Настройки системы
                    <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                    <li><a href="#">Модули</a></li>
                        <li class="divider"></li>
                    <li><a href="#">Конфигурация</a></li>
                        <li class="divider"></li>
                    <li><a href="#">Экспорт/Импорт</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Разное</a></li>
                    </ul>
                </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>&copy; 2006 - 2012 by Zend Technologies Ltd. All rights reserved.</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
