<?php 
$title = '1. Получите отчет';
$this->headTitle($title);
$this->headLink()->prependStylesheet('/css/report.css',
                                     'screen',
                                     true,
                                     array('id' => 'report_stylesheet'));
?>
<h2><?php echo $this->escape($title); ?></h2>

<p>Запрос №: 01 от 11.02.2012 15:35</p>
<ul class="prop">
  <li>ФИО <span>Андрей Анатольевич Батарин</span></li>
  <li>Дата рождения: <span>02.12.1985</span></li>
  <li>Пол: <span>Мужской</span></li>
</ul>
<p>&nbsp;</p>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <th><span class="part">Счета</span></th>
    <th><span class="box-cell">Итог</span></th>
    <th><span class="box-cell">Договоры</span></th>
    <th><span class="box-cell">Баланс</span></th>
    <th><span class="box-cell">Открыт</span></th>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Всего: <span>6</span></td>
    <td>Кредитный лимит: <span>RUB 777824</span></td>
    <td>Текущий: <span>RUB 944259</span></td>
    <td>Последний: <span>11.01.2011</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Негативных: <span>1</span></td>
    <td><span>RUR 0</span></td>
    <td><span>RUR 0</span></td>
    <td>Первый: <span>06.12.2006</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Открытых: <span>2</span></td>
    <td>Ежемесячгые выплаты: <span>RUB 0</span></td>
    <td>Задолжность: <span>RUB 0</span></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><span>RUR 0</span></td>
    <td><span>RUR 0</span></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Просрочено: <span>RUB 0</span></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>RUR <span>0</span></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th class="part">Запросы</th>
    <th>Всего</th>
    <th>За 30 дней</th>
    <th>За 24 мес.</th>
    <th>Последний</th>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><span>30</span></td>
    <td><span>3</span></td>
    <td><span>24</span></td>
    <td><span>последние 14 дней</span></td>
  </tr>
</table>
<p>&nbsp;</p>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <th class="part">Телефон</th>
    <th>Домашний</th>
    <th>Рабочий</th>
    <th>Сотовый</th>
    <th>&nbsp;</th>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><span>(8482) 376765</span></td>
    <td><span>нет данных</span></td>
    <td><span>нет данных</span></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th class="part">Счета</th>
    <th>Легенда</th>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><div class="t-inline t0">0</div>
    Новый, оценка невозможна</td>
    <td><div class="t-inline t2">2</div>
    Просрочка от 30 до 59 дней</td>
    <td><div class="t-inline t5">5</div>
    Просрочка более 120 дней</td>
    <td>Безнадежный долго / передано на взыскание</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><div class="t-inline t1">1</div>
    Оплата без просрочек</td>
    <td><div class="t-inline t3">3</div>
    Просрочка от 60 до 89 дней</td>
    <td><div class="t-inline t7">7</div>
    Регулярн.консолидир.платежи</td>
    <td><div class="t-inline t-">-</div>
    Нет данных</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><div class="t-inline tA">A</div>
    Просрочка от 1 до 29 дней</td>
    <td><div class="t-inline t4">4</div>
    Просрочка от 90 до 119 дней</td>
    <td><div class="t-inline t8">8</div>
    Взыскание оплаты залогом</td>
    <td>&nbsp;</td>
  </tr><tbody class="odd">

  <tr>
    <th>&nbsp;</th>
    <th>Счет</th>
    <th>Договор</th>
    <th>Состояние</th>
    <th>Баланс</th>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Вид: <span>Автокредит</span></td>
    <td>Размер/лимит: <span>RUB 522000</span></td>
    <td>Открыт: <span>11.03.2008</span></td>
    <td>Всего выплачено: <span>RUB 639573</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Отношение: <span>Личный</span></td>
    <td>Финальн.платеж: <span>11.03.2013</span></td>
    <td>Статус: <span>Счет закрыт</span></td>
    <td>Задолжность: <span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Финальн.платеж %%: <span>11.03.2013</span></td>
    <td>Дата статуса: <span>14.06.2011</span></td>
    <td>Просрочено: <span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Выплата осн.: <span>Ежемесячно</span></td>
    <td>Последн.выплата: <span>14.06.2011</span></td>
    <td>След.платеж: <span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Выплата %%: <span>Ежемесячно</span></td>
    <td>Послед.обновление: <span>19.07.2011</span></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Обеспечение: <span>нет данных</span></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Просроч платежей: <span>1</span></td>
    <td colspan="3">Своевременность платежей (за 56 мес, последний &#8212; слева)</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Просрочек от 30 до 59 дн.: <span>1</span></td>
    <td colspan="3" rowspan="3"><ul class="history">
      <li>
        <div class="t1">1</div>
        И
</li>
      <li>
        <div class="t1">1</div>
        М
</li>
      <li>
        <div class="t1">1</div>
А</li>
      <li>
        <div class="t1">1</div>
        Ф</li>
      <li>
        <div class="t0">0</div>
        11</li>
    </ul></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Просрочек от 60 до 89 дн.: <span>0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Просрочек более, чем на 90 дн.: <span>0</span></td>
  </tr>
</tbody>
<tbody>

  <tr>
    <th>&nbsp;</th>
    <th>Счет</th>
    <th>Договор</th>
    <th>Состояние</th>
    <th>Баланс</th>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Вид: <span>Автокредит</span></td>
    <td>Размер/лимит: <span>RUB 522000</span></td>
    <td>Открыт: <span>11.03.2008</span></td>
    <td>Всего выплачено: <span>RUB 639573</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Отношение: <span>Личный</span></td>
    <td>Финальн.платеж: <span>11.03.2013</span></td>
    <td>Статус: <span>Счет закрыт</span></td>
    <td>Задолжность: <span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Финальн.платеж %%: <span>11.03.2013</span></td>
    <td>Дата статуса: <span>14.06.2011</span></td>
    <td>Просрочено: <span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Выплата осн.: <span>Ежемесячно</span></td>
    <td>Последн.выплата: <span>14.06.2011</span></td>
    <td>След.платеж: <span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Выплата %%: <span>Ежемесячно</span></td>
    <td>Послед.обновление: <span>19.07.2011</span></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Обеспечение: <span>нет данных</span></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Просроч платежей: <span>1</span></td>
    <td colspan="3">Своевременность платежей (за 56 мес, последний &#8212; слева)</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Просрочек от 30 до 59 дн.: <span>1</span></td>
    <td colspan="3" rowspan="3"><ul class="history">
      <li>
        <div class="t1">1</div>
        И
</li>
      <li>
        <div class="t1">1</div>
        М
</li>
      <li>
        <div class="t1">1</div>
А</li>
      <li>
        <div class="t1">1</div>
        Ф</li>
      <li>
        <div class="t0">0</div>
        11</li>
    </ul></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Просрочек от 60 до 89 дн.: <span>0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Просрочек более, чем на 90 дн.: <span>0</span></td>
  </tr>
</tbody>
<tbody class="odd">

  <tr>
    <th>&nbsp;</th>
    <th>Счет</th>
    <th>Договор</th>
    <th>Состояние</th>
    <th>Баланс</th>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Вид: <span>Автокредит</span></td>
    <td>Размер/лимит: <span>RUB 522000</span></td>
    <td>Открыт: <span>11.03.2008</span></td>
    <td>Всего выплачено: <span>RUB 639573</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Отношение: <span>Личный</span></td>
    <td>Финальн.платеж: <span>11.03.2013</span></td>
    <td>Статус: <span>Счет закрыт</span></td>
    <td>Задолжность: <span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Финальн.платеж %%: <span>11.03.2013</span></td>
    <td>Дата статуса: <span>14.06.2011</span></td>
    <td>Просрочено: <span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Выплата осн.: <span>Ежемесячно</span></td>
    <td>Последн.выплата: <span>14.06.2011</span></td>
    <td>След.платеж: <span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Выплата %%: <span>Ежемесячно</span></td>
    <td>Послед.обновление: <span>19.07.2011</span></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Обеспечение: <span>нет данных</span></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Просроч платежей: <span>1</span></td>
    <td colspan="3">Своевременность платежей (за 56 мес, последний &#8212; слева)</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Просрочек от 30 до 59 дн.: <span>1</span></td>
    <td colspan="3" rowspan="3"><ul class="history">
      <li>
        <div class="t1">1</div>
        И
</li>
      <li>
        <div class="t1">1</div>
        М
</li>
      <li>
        <div class="t1">1</div>
А</li>
      <li>
        <div class="t1">1</div>
        Ф</li>
      <li>
        <div class="t0">0</div>
        11</li>
    </ul></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Просрочек от 60 до 89 дн.: <span>0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>Просрочек более, чем на 90 дн.: <span>0</span></td>
  </tr>
</tbody>
</table>
<p>&nbsp;</p>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <th class="part">Запросы</th>
    <th>Период</th>
    <th>Цель запроса</th>
    <th>Объем кредита</th>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><span>последние 14 дней</span></td>
    <td><span>Просмотр счета</span></td>
    <td><span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><span>последние 14 дней</span></td>
    <td><span>Просмотр счета</span></td>
    <td><span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><span>последние 14 дней</span></td>
    <td><span>Просмотр счета</span></td>
    <td><span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><span>последние 14 дней</span></td>
    <td><span>Просмотр счета</span></td>
    <td><span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><span>последние 14 дней</span></td>
    <td><span>Просмотр счета</span></td>
    <td><span>RUB 0</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><span>последние 14 дней</span></td>
    <td><span>Просмотр счета</span></td>
    <td><span>RUB 0</span></td>
  </tr>
</table>


<form id="form1" name="form" method="post" action="<?php echo $this->url('default');?>">
  <input type="hidden" name="result" value="0">
  <input type="button" class="button green" value="Подтвердить" onclick="this.form.result.value = 1; this.form.submit();"/>
  <input type="button" class="button red" value="Отклонить" onclick="this.form.submit();" />
</form>
<!-- <?php echo $this->CurrentInfo($appeal_id);?> -->