<?php 
$title = 'Данные о работе.';
$this->headTitle($title);
?>
<?php $this->headStyle()->captureStart() ?>
form#client_data span {
    width: 170px;
}
<?php $this->headStyle()->captureEnd() ?>
<?php $this->headScript()->captureStart() ?>
$(document).ready(function () {
		$('.alter')
			.focusin(function () {
					if (this.alt=='') {
						this.alt = this.value;
						this.value = '';
						$(this).removeClass('alter');
					}
				})
			.focusout(function () {
					if (this.value=='') {
						this.value = this.alt;
						this.alt = '';
						$(this).addClass('alter');
					}
				});


		var btns = $('form div div');
		btns.find('a.confirm').click(function () {
				$(this).parent().find('input[type*=checkbox]')[0].checked = true;
				$(this).remove();
			});
		btns.find('a:first').click(function () {
				var labelBox = $(this).parent().parent();
				labelBox.find('input').removeClass('hidden')
				labelBox.find('div').remove();
			});

		$('a').click(function () {
				var ok = true;
				$('input[type*=checkbox]').each(function () {
						if (!this.checked) {
							ok = false;
						}
					});

				if (ok) {
					$('input[type*=submit]').removeAttr('disabled');
				}
			});
	});
<?php $this->headScript()->captureEnd() ?>


<h2><?php echo $this->escape($title); ?></h2>
   <div style="width: 600px;"> <?php echo $form; ?> </div>

<!--
<?php //echo $this->CurrentInfo($appeal_id);?>
<div class="">
<h4>Суммарная информация</h4>
<blockquote><small>Кредитный продукт:</small> Краткосрочный кредит.
</div> -->